Ajout de l'affichage de l'image dans la page profil
TommyRiquet/ProjetIntegration pull request #122
Opened 2022-11-14 13:52 UTC by KeviinKeurvels

2022-11-14 15:36 UTC, Lopidurs requested changes
Bha alors on a pas lancer les tests avant de pull request????

2022-11-14 16:50 UTC, KeviinKeurvels commented
> Bha alors on a pas lancer les tests avant de pull request????

Bha je l'ai dit enfaite à cause d'un bus que je devais prendre

2022-11-15 12:09 UTC, TommyRiquet commented
T'es sur que supprimer le test est la meilleur solution ?

2022-11-15 18:51 UTC, Lopidurs requested changes
Impossible de changer mes information:
J'ai un profile avec aucune image d'enregistrer c'est peut-être pour ça...
![image](https://user-images.githubusercontent.com/62069633/202001708-de532ccb-aeeb-44cf-9121-60f85e6068d1.png)

2022-11-15 19:23 UTC, Lopidurs approved these changes
Merci pour les 20e

2022-11-15 19:23 UTC, merged