US #23 Page administration
TommyRiquet/ProjetIntegration pull request #127
Opened 2022-11-15 17:36 UTC by RaphaelMarto

complétion de 4 Us car lié l'une a l'autre 
US #23 Page admin
US #28 fenêtre signalement avis
US #26 fenêtre signalement annocne
US #27 fenêtre signalement utilisateur

2022-11-15 18:27 UTC, TommyRiquet submitted a review, later dismissed
## Admin Model 
- Redondence de données entre clientID - ClientName et SuspectId et SuspectName
- Mauvais Type de données  
![image](https://user-images.githubusercontent.com/71312500/202002203-c8d1ef12-9434-4030-9b91-030990eacdcc.png)


## Testing
- Pas de test Frontend
- Pas de test Backend

## Gestion de projet 
- Aucun critères d'acceptations n'a été approuvé  
- Les US ne sont pas dans le sprint backlog

2022-11-24 09:59 UTC, KeviinKeurvels requested changes
- ligne 14 et 28 du fichier Admin.js dans routes: enlevé la virgule car pas d'argument après
- checker pour la requête pour include la même table 2 fois:
https://stackoverflow.com/questions/51480266/joining-same-table-multiple-times-with-sequelize

2022-12-01 10:40 UTC, KeviinKeurvels requested changes
- Problème dans la route car les noms sont pas affichés dans les filtres
- Ajouter un filtre pour les dates dans la requête comme ça la page affichera les signalements les plus récents en premier
- Changer pour mettre toutes les requêtes en SQL et ne pas faire une partie SQL et une partie sequelize

2022-12-03 11:57 UTC, KeviinKeurvels requested changes
- Cela serait plus normal de trier par ordre du plus récent au plus ancien signalement:
![image](https://user-images.githubusercontent.com/93135833/205439770-0bb55b0a-4fb9-40d7-8859-d9eb5bf229f8.png)  
- D'ailleurs, tu tries sur la date de création mais tu affiches la date d'update, est-ce normal ?

- Sinon, pour le reste c'est ok

2022-12-03 15:42 UTC, RaphaelMarto commented
Donc tu veux que le premier signalement de la liste que tu vois soit le plus ancien ? parce que pour l'instant c'est le plus récent en premier. Et pour la date d'update ou de création cela ne change rien car on peut pas modifier un report.

2022-12-03 16:57 UTC, KeviinKeurvels approved these changes
- Tu as bien appliqué ce que je t'ai dit oralement avec le format de la date à afficher

2022-12-03 16:58 UTC, merged