US13 - Modification du profil
TommyRiquet/ProjetIntegration pull request #142
Opened 2022-11-17 21:19 UTC by KeviinKeurvels

Voilà vous pouvez changer les informations de votre profil
À savoir que l'image ne peut pas être changée car le client a dit qu'on enlevait la photo de profil perso. Il y a donc une autre US pour mettre des picto à la place.
Have fun !

2022-11-18 17:55 UTC, TommyRiquet commented
Arrête de faire ça par pitié 😄   
![image](https://user-images.githubusercontent.com/71312500/202770557-5ef9d249-d18a-44b2-877a-0522076f1de1.png)

2022-11-18 21:02 UTC, TommyRiquet requested changes
## console.log oublié 
Console.log oublié à la ligne 39 du fichier Account.js 
Console.log oublié à la ligne 68 du fichier Account.js 

## Problème lors du refresh de la page Account
Je modifie un champ et que je valide : 
- Lorsque je refresh la page, les modifications sont effacés 
   - Problème : pas de modification de l'object stocké dans le localStorage lors de l'update dans la DB

## Je ne sais pas si c'est censé être la ça
![image](https://user-images.githubusercontent.com/71312500/202801683-cb57ae6a-701c-424e-bdb7-112219bf0405.png)

2022-11-19 11:43 UTC, KeviinKeurvels commented
> ## console.log oublié
> Console.log oublié à la ligne 39 du fichier Account.js Console.log oublié à la ligne 68 du fichier Account.js
> 
> ## Problème lors du refresh de la page Account
> Je modifie un champ et que je valide :
> 
> * Lorsque je refresh la page, les modifications sont effacés
>   
>   * Problème : pas de modification de l'object stocké dans le localStorage lors de l'update dans la DB
> 
> ## Je ne sais pas si c'est censé être la ça
> ![image](https://user-images.githubusercontent.com/71312500/202801683-cb57ae6a-701c-424e-bdb7-112219bf0405.png)

Changements effectués.
Et oui c'est logique pour le "Modifier la photo de profil". C'est parce que je vais bientôt faire la modification de photo de profil donc autant le laisser.

2022-11-21 02:38 UTC, TommyRiquet approved these changes
Bien

2022-11-21 13:31 UTC, merged