Footer #77
TommyRiquet/ProjetIntegration pull request #187
Opened 2022-12-07 14:46 UTC by RaphaelMarto

Ajout du footer dans la page Home 
US #77

2022-12-07 17:27 UTC, KeviinKeurvels requested changes
- ça serait intéressant de l'avoir sur toutes les pages
- ça serait mieux de l'avoir dans le même bleu que la barre de navigation
- Remplacement de la page Contact par directement l'adresse mail

2022-12-13 17:54 UTC, KeviinKeurvels reviewed
juste attention la route /mentionlegales est maintenant /policy

2022-12-14 20:31 UTC, TommyRiquet commented
Si cette pr est nécessaire, fait un rebase
voir #208

2022-12-14 23:09 UTC, Lopidurs approved these changes
mmmm ok

2022-12-14 23:10 UTC, merged