Nathan
TommyRiquet/ProjetIntegration pull request #215
Opened 2022-12-15 12:46 UTC by Lopidurs

2022-12-15 16:16 UTC, mquadu reviewed
touche pas à ça p'tit con!!

2022-12-17 11:24 UTC, TommyRiquet commented
Normal que dans la #213 , y a déja le commit [2c7f2e4](https://github.com/TommyRiquet/ProjetIntegration/pull/215/commits/2c7f2e49428422acdc1d92cf404f56af9e7a6299) ?

2022-12-20 16:31 UTC, TommyRiquet commented
> Normal que dans la #213 , y a déja le commit [2c7f2e4](https://github.com/TommyRiquet/ProjetIntegration/pull/215/commits/2c7f2e49428422acdc1d92cf404f56af9e7a6299) ?

@Lopidurs

2022-12-20 18:02 UTC, KeviinKeurvels requested changes
- problème lors de création d'un nouveau compte:  
![image](https://user-images.githubusercontent.com/93135833/208734658-352d8930-597d-4ab2-b5de-754135de1c6d.png)
- on ne pas se connecter après
- PhotoLink est utile pour le système d'avatars
- il y a un fichier qu'on ne sait pas à quoi il sert

2022-12-20 19:40 UTC, KeviinKeurvels approved these changes
Okey tout fonctionne bien

2022-12-20 19:40 UTC, merged