création profil animal
TommyRiquet/ProjetIntegration pull request #50
Opened 2022-10-05 19:36 UTC by Lopidurs

2022-10-05 19:54 UTC, KeviinKeurvels reviewed
Il faut changer:
- les options "titres" par optgroup
- pourquoi pas ne pas mettre des "required" dans les champs du formulaire
- mettre les "values" en anglais (conventions !)

2022-10-06 06:33 UTC, TommyRiquet reviewed
**Pas de test**

**Formulaire pas centré verticalement**

**Bouton "Inscrire l'animal" pas responsive**

**Non respect des conventions de la structure de fichiers**
=> Component FormPet ne sera utilisé qu'une seule fois

2022-10-16 13:16 UTC, TommyRiquet requested changes
**Tous les champs passent au rouge lors de l'encodage** 
**Non respect de la maquette**
=> formulaire non centré verticalement
=> Bouton Inscrire l'animal = Enregistrer 
=> Pas de champ pour ajouter une photo
=> Espèce d'animal != champ libre

2022-10-20 08:51 UTC, RaphaelMarto requested changes
Supprimer formPet et mettre tout dans petCreation

2022-10-20 09:26 UTC, TommyRiquet requested changes
**Faute dans Type animal**
Deux fois 'Lapin'

**Même remarque plus haut : le champ Race est libre**
Proposer les races en fonction des types

**Bouton pas centré horizontalement**

**Voir PO pour la structure du formulaire**

2022-10-20 10:44 UTC, TommyRiquet submitted a review, later dismissed
En vrai, insha'allah

2022-10-20 10:51 UTC, TommyRiquet approved these changes
super

2022-10-20 10:54 UTC, Lopidurs commented
jpp

2022-10-20 10:55 UTC, Lopidurs commented
github à chier

2022-10-20 14:49 UTC, closed without merging

2022-10-20 14:50 UTC, TommyRiquet commented
Rest in peace